version: '3'

volumes:
  kittygram_pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data
  backend:
    image: japrojah/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: japrojah/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: japrojah/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 9000:80

